Rails:
  Enabled: true
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
Style/Documentation:
  Enabled: false
Style/FileName:
  Exclude:
    - 'Gemfile'
